### ISSUE TITLE
Panic in http_req::request::Request::send on fetching some websites

### ISSUE THREAD

**Issue by Shnatsel** [jayjamesjay/http_req#29]
http_req panics on fetching either of these websites: `hit.de`, `uhu.es`

Backtrace:
```
thread 'main' panicked at 'slice index starts at 18446744073709551614 but ends at 2', src/libcore/slice/mod.rs:2680:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1057
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:195
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:215
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:376
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::slice::slice_index_order_fail
             at src/libcore/slice/mod.rs:2680
  14: http_req::request::Request::send
  15: http_req_test::main
  16: std::rt::lang_start::{{closure}}
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:79
  20: std::panicking::try
             at src/libstd/panicking.rs:272
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  23: std::rt::lang_start
  24: __libc_start_main
  25: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Tested on http_req version 0.5.4

**Comment by jayjamesjay** [comment]
I've tested those sites on my own and I cannot reproduce the error.

My testing code for `hit.de`:
```rust
use http_req::request;

fn main() {
    let mut writer = Vec::new(); //container for body of a response
    let res = request::get("https://hit.de", &mut writer).unwrap();

    println!("Status: {} {}", res.status_code(), res.reason());
}
```
Result: `Status: 301 Moved Permanently`

My testing code for `uhu.es`:
```rust
use http_req::request;

fn main() {
    let mut writer = Vec::new(); //container for body of a response
    let res = request::get("http://uhu.es", &mut writer).unwrap();

    println!("Status: {} {}", res.status_code(), res.reason());
}
```
Result: `Status: 200 OK`

Could you give more details about your specific case?

**Comment by Arnavion** [comment]
Might be https://github.com/jayjamesjay/http_req/blob/bf05695878f93fc91c7a4c30de0279fe1bb3cfc5/src/request.rs#L35 - I don't see how it's guaranteed that `buf.len() - val.len()` will be >= 0. `val.len()` is the length of `CR_LF_2`, so 4, and a short enough read for filling `pre_buf` plus the one byte from `reader.bytes()` will not necessarily make `buf` have 4 or more bytes.

Edit: Indeed:

```rust
#![allow(const_err)]

fn main() {
    let buf: &[u8; 2] = &[0; 2];
    let _ = &buf[(2 - 4)..];
}
```

[reproduces the OP panic message,](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=bb1ddb26ab8129c42e6c74663f0e27cf) suggesting `buf` only has two bytes in it at that point.

Edit 2: Also, `buf.ends_with(val)` is a much simpler way to write that condition.

**Comment by jayjamesjay** [comment]
@Arnavion you're completely right. Thank you.
I've applied this fix in commit [update deps, docs fix, fn copy_until fix](https://github.com/jayjamesjay/http_req/commit/187e1a75ed1f5c18fc3fe9c924afce3657c4bfad) .
